### ISSUE TITLE
Support for Blinds as Window Covering

### ISSUE THREAD

**Issue by rywalters** [toggledbits/Switchboard-Vera#3]
I use the iBlinds retrofit product for my blinds, which works great but has one big limitation with Vera -- the "open" command maps to 100% open, which for blinds is actually...closed (the opposite of 0% closed). It'd be awesome if I could create a virtual window covering that could be configured to map the "open" command to 50%. And because some blinds work better closed at 100% rather than 0%, it'd be cool if the "close" command could be set to one of those values as well.

**Comment by rywalters** [comment]
Ah, maybe all of that can and should just be built in Reactor...

**Comment by toggledbits** [comment]
Not sure what this has to do with Switchboard, and it is definitely nothing to do with Reactor. This sounds like a Vera problem for them to solve?

**Comment by rywalters** [comment]
Agreed. Most things I do with Vera lately are working around problems...

Thanks for all your work!

**Comment by toggledbits** [comment]
Sadly there's a lot of that. I don't know what your transition plans are, but I have an expanded version of Reactor that works with Vera, Ezlo, Home Assistant, Hubitat, and MQTT. You can write rules without really caring what hub has the device(s), so it facilitates the transition away from Vera as a journey rather than a fire drill event, and gives you choice for what hub best supports the devices you have. Info here: https://reactor.toggledbits.com/

**Comment by rywalters** [comment]
I've been looking at that, actually and am planning to install it and try it out soon. I really enjoy Reactor on Vera. It's given it new life.
